<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Done   Computer BlackBerry PlayBook has been updated</name>
   <tag></tag>
   <elementGuidId>59857623-16db-47c1-b73e-17a8818e5fa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.alert-message.warning</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>77d0113f-f4c4-4de6-8a53-5d6e8fb48fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert-message warning</value>
      <webElementGuid>c7bec9b2-82fe-4c50-a052-d94ca274dfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done !  Computer BlackBerry PlayBook has been updated</value>
      <webElementGuid>dfba7d80-2c46-47e6-89c8-39151b00faab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;alert-message warning&quot;]</value>
      <webElementGuid>96d1fef6-c3d0-4ae5-a7e3-bd138a1a2eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfee54dd-9c83-4855-b8d5-d7ba30257d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert-message warning</value>
      <webElementGuid>dace80a0-0579-4c4c-8698-fd9d194473ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done !  Computer BlackBerry PlayBook has been updated</value>
      <webElementGuid>2b7da562-f9d5-43bd-b04c-9167f3632cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;alert-message warning&quot;]</value>
      <webElementGuid>5e224d1e-edb3-44aa-8ae6-7e1d6995e6cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div</value>
      <webElementGuid>99aa8ea9-c154-4041-a4de-1e95ddbaf329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Computer database'])[1]/following::div[1]</value>
      <webElementGuid>44f56554-5e58-4ca5-8d5f-f2c6c0276cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a new computer'])[1]/preceding::div[1]</value>
      <webElementGuid>eee5f892-d232-425f-a212-d8876d8c74db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Computer BlackBerry PlayBook has been updated']/parent::*</value>
      <webElementGuid>5473118e-18ec-41cb-ad47-c8a59aea6ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>c2b7f29a-2079-48bc-9ed1-9d9dc04e51b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Done !  Computer BlackBerry PlayBook has been updated' or . = 'Done !  Computer BlackBerry PlayBook has been updated')]</value>
      <webElementGuid>47c20d1e-1473-4505-b40d-adf58cccf38e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
