<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Computer database_f</name>
   <tag></tag>
   <elementGuidId>d3cf2d7d-1e7b-4237-8423-c56214dd0437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e43b1ea8-be0d-4139-8347-6f38be7433be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>066fc910-5dbc-44f2-a770-4a1d9c4d049f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>4ce114ae-051b-4800-aa43-77e863f1598f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f</value>
      <webElementGuid>fd3a337c-b24f-4347-b61f-ab00522e7a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter by computer name...</value>
      <webElementGuid>69f2b9bf-c0a6-4f7d-8948-cc2df3293ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b5522641-02b2-4cf3-bba1-a9048219c1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchbox&quot;)</value>
      <webElementGuid>c3029eb9-b3f2-477b-bb98-f9943a6b9301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>676f03d8-077d-4b48-a8f3-cc03b4d5e8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>fc41e3df-55c4-4698-a20c-9beb8fe619dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>2cbc46c6-68df-4034-a16e-0f00b2e52727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f</value>
      <webElementGuid>87d94c4f-5ae7-4fd8-ac00-8c961fc82964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter by computer name...</value>
      <webElementGuid>1447b1e8-ca50-47a4-91d5-22e98988be70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>4b41eb5c-499c-4ade-bb67-ee5450eaf715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchbox&quot;)</value>
      <webElementGuid>395e78d4-15a2-4fde-afbb-7edfcc831363</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchbox']</value>
      <webElementGuid>e352d9b1-a59c-49b2-91f6-fc47de9843e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actions']/form/input</value>
      <webElementGuid>fe544105-a64e-413b-9c5c-55657881a6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>61cabafe-e158-47d7-a522-4e894c9a75d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'searchbox' and @name = 'f' and @placeholder = 'Filter by computer name...']</value>
      <webElementGuid>e214bbad-9339-421a-a64a-511ea90c3c8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
