<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select a date_day</name>
   <tag></tag>
   <elementGuidId>90f3a944-2d2f-4692-a406-2ca73e7f6cbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='day']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e4b9c06-ad1c-4d65-ae1e-0ebd2f076989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>391fa0e3-0415-46c7-80fa-8f1e3cf7b765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>36af5a41-34e1-4d59-9017-e03228b0ad24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>c6051c41-b980-4316-bdbd-deba6b6c5742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;day&quot;)</value>
      <webElementGuid>be53ebf6-bb0e-471b-b8d9-b0e9d40cb7f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='day']</value>
      <webElementGuid>7207c03e-417a-4e2e-92a8-a33645ac1a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[11]</value>
      <webElementGuid>bda2acbe-b373-4cd1-acac-127dbfeb1a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'day' and @name = 'day']</value>
      <webElementGuid>e1098309-c494-4b1a-a415-03e96b71c218</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
