<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select a file_myfile</name>
   <tag></tag>
   <elementGuidId>cfa70e43-43b6-41e8-9442-1774ee201aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myfile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='myfile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63ded7f1-0244-44e7-ba9e-fcd0bc4509d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>75635bf3-ceae-47e3-9699-aa6941302d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myfile</value>
      <webElementGuid>5588aa88-f1dd-4751-aa77-13fa2cd5c04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>myfile</value>
      <webElementGuid>16d571b4-fa29-4dc3-a407-08d5783dd675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myfile&quot;)</value>
      <webElementGuid>17fc9576-e1ac-4802-9f43-72bb6ff47a4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='myfile']</value>
      <webElementGuid>254c9366-86ce-4466-b808-8d5dd850b2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[13]</value>
      <webElementGuid>a59aadbe-8678-4841-b0a3-dc8e13c511dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'myfile' and @name = 'myfile']</value>
      <webElementGuid>459b1fe9-79b5-4e61-bca9-e35ad0e3e5fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
