<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_fname</name>
   <tag></tag>
   <elementGuidId>02941380-1ed3-45be-939c-795c1f118ea0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed6af724-bc90-4238-a336-ec36dd5a8891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af09f2be-6f17-4f0a-bc1c-e238632d65da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fname</value>
      <webElementGuid>af8d870b-5a3b-46ed-be53-e759a59cce53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>1345b5ef-6ed3-4e63-b629-869f3f0c593d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fname</value>
      <webElementGuid>66bf5a6b-792b-48eb-aef4-d96b94ac140e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fname&quot;)</value>
      <webElementGuid>f249b4ae-18b6-45a3-823c-d4f0d447667c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fname']</value>
      <webElementGuid>af27a2d1-d683-444e-af56-9ae9310d754b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>6957a903-dc6c-4323-b461-91f22bcac5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fname' and @placeholder = 'Text' and @name = 'fname']</value>
      <webElementGuid>ae70969d-3f14-4fff-aaa8-7bb7dfee02f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
