<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_lname</name>
   <tag></tag>
   <elementGuidId>eedde8ca-4c6e-40ac-abde-b4fd7fc67783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2890d7ce-15b8-4ff3-8b53-6d9d82520680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e886f177-d83b-4afa-b1f2-8a8875ed8a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lname</value>
      <webElementGuid>58aac890-cd57-4966-bbcc-71a01188d982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>c29efbac-fa6d-441a-8984-28210fdc6cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lname</value>
      <webElementGuid>8a69ab52-8066-4ecf-9438-eb8029b436bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lname&quot;)</value>
      <webElementGuid>2570afcb-2028-447d-9d06-569ec0b30645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lname']</value>
      <webElementGuid>825eda05-ef46-4a4f-9497-6b29260b2f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input[2]</value>
      <webElementGuid>cc6cf00c-45dc-423f-bd95-71ecb30c52b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lname' and @placeholder = 'Text' and @name = 'lname']</value>
      <webElementGuid>305a3f55-b238-4d3d-b25a-466e6325b69f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
